#############################
# 5Z Cod
# Survey Sinclair Z
# July 1, 2021
# Author: Caira Clark / Irene Andrushchenko / Chris Legault
#############################

require(ggplot2)
require(tidyr)
require(dplyr)
require(reshape2)
require(Hmisc)
require(here)

#Load the function to calculate Sinclair Z--------------------

# estimates catch curve Z using 4 year moving window with cohort-specific coefficients
# matrix has year in rows and age in columns
calc_Sinclair_Z <- function(mat){
  res <- list()
  mat <- as.matrix(mat)
  if (all(is.na(mat))){
    res$error <- TRUE
    return(res)
  }
  year <- as.numeric(rownames(mat))
  age <- as.numeric(colnames(mat))
  ny <- length(year)
  est.Sinclair.Z <- matrix(NA, nrow=(ny-3), ncol=3)
  plot.year <- rep(NA, ny-3)
  for (i in 1:(ny-3)){
    submat <- mat[year %in% year[i:(i+3)],]
    data <- melt(submat)
    colnames(data) <- c("Year","Age","Value")
    data$cohort <- data$Year - data$Age
    data$Value[data$Value == 0] <- NA
    data <- data[!is.na(data$Value) ,]
    data$lnVal <- log(data$Value)
    can.calc <- FALSE
    if (length(data[,1]) >= 2){
      if (max(table(data$cohort)) >= 3){
        can.calc <- TRUE
      }
    }
    if (can.calc == TRUE){
      my.lm <- lm(data$lnVal ~ as.factor(data$cohort) + data$Age)
      data$pred <- predict(my.lm)
      data$resid <- residuals(my.lm)
      res[[i]] <- data
      est.Sinclair.Z[i,1] <- -1 * my.lm$coefficients[names(my.lm$coefficients) == "data$Age"]
      est.Sinclair.Z[i,2:3] <- -1 * rev(confint(my.lm, "data$Age", level=0.90))
    }
    else{  
      res[[i]] <- data
      est.Sinclair.Z[i,] <- rep(NA, 3)
    }
    plot.year[i] <- year[i] + 1.5
  }
  res$est.Sinclair.Z <- est.Sinclair.Z
  res$plot.year <- plot.year
  res$error <- FALSE
  return(res)
}

##DFO Survey (ages 6-9)------------------------

CAA <- read.csv(here("data/Survey CAA/dfo_survey_caa.csv"))
Sindex <- CAA %>% select(a6, a7, a8, a9)
Sindex<-as.matrix(Sindex)
rownames(Sindex)<-seq(1986, 2021, 1)
colnames(Sindex)<-c(6,7,8,9)


# function to plot the results from calc_Sinclair_Z
# res is a list generated by the function calc_Sinclair_Z
dfoplot_Sinclair_Z <- function(res,est.Z.name,regress.name,resid.name,my.title=NA){
  # first the plot of estimated Z with CI over time
  est.Z <- res$est.Sinclair.Z
  if (!all(is.na(est.Z))){
    plot.year <- res$plot.year
    errbar(plot.year,est.Z[,1],est.Z[,3],est.Z[,2],ylim=c(-1,4),xlab="Year",ylab="Sinclair Z")
    abline(h=0)
    title(main="DFO ages 6-9")
  }
}

est_Sinclair_Z<-calc_Sinclair_Z(Sindex)
p <- dfoplot_Sinclair_Z(est_Sinclair_Z)

#This is the graph of Sinclair Z that is included in the document

est_Sinclair_Z

#This renames it for the faceted plot at the end
est_Sinclair_Z_DFO_6_9<-est_Sinclair_Z

##NMFS Spring Survey (ages 5-9)---------------------

CAA <- read.csv(here("data/Survey CAA/nmfsspr_survey_caa.csv"))
Sindex <- CAA %>% select(a5, a6, a7, a8, a9)
Sindex<-as.matrix(Sindex)
rownames(Sindex)<-seq(1970, 2022, 1)
colnames(Sindex)<-c(5,6,7,8,9)


# function to plot the results from calc_Sinclair_Z
# res is a list generated by the function calc_Sinclair_Z
nmfssprplot_Sinclair_Z <- function(res,est.Z.name,regress.name,resid.name,my.title=NA){
  # first the plot of estimated Z with CI over time
  est.Z <- res$est.Sinclair.Z
  if (!all(is.na(est.Z))){
    plot.year <- res$plot.year
    errbar(plot.year,est.Z[,1],est.Z[,3],est.Z[,2],ylim=c(-1,4),xlab="Year",ylab="Sinclair Z")
    abline(h=0)
    title(main="NMFS Spring ages 5-9")
  }
}

est_Sinclair_Z<-calc_Sinclair_Z(Sindex)
p <- nmfssprplot_Sinclair_Z(est_Sinclair_Z)
p
#This is the graph of Sinclair Z that is included in the document

est_Sinclair_Z

#This renames it for the faceted plot at the end
est_Sinclair_Z_NMFS_Spring_5_9<-est_Sinclair_Z

#NMFS Fall Survey (ages 3-6)---------------------------

CAA <- read.csv(here("data/Survey CAA/nmfsfall_survey_caa.csv"))
CAA<-subset(CAA, Year>1977)
Sindex <- CAA %>% select(a3, a4, a5, a6)
Sindex<-as.matrix(Sindex)
rownames(Sindex)<-seq(1978, 2021, 1)
colnames(Sindex)<-c(3,4,5,6)


# function to plot the results from calc_Sinclair_Z
# res is a list generated by the function calc_Sinclair_Z
nmfsfallplot_Sinclair_Z <- function(res,est.Z.name,regress.name,resid.name,my.title=NA){
  # first the plot of estimated Z with CI over time
  est.Z <- res$est.Sinclair.Z
  if (!all(is.na(est.Z))){
    plot.year <- res$plot.year
    errbar(plot.year,est.Z[,1],est.Z[,3],est.Z[,2],ylim=c(-1,4),xlab="Year",ylab="Sinclair Z")
    abline(h=0)
    title(main="NMFS Fall ages 3-6")
  }
}

est_Sinclair_Z<-calc_Sinclair_Z(Sindex)
p <- nmfsfallplot_Sinclair_Z(est_Sinclair_Z)

#This is the graph of Sinclair Z that is included in the document

est_Sinclair_Z

#This renames it for the faceted plot at the end
est_Sinclair_Z_NMFS_Fall_3_6<-est_Sinclair_Z


#Faceted plot. I'm sure there is a more elloquent way of doing this.
sub<-est_Sinclair_Z_DFO_6_9$est.Sinclair.Z
subA<-est_Sinclair_Z_DFO_6_9$plot.year
DFO_6_9<-as.data.frame(cbind(subA,sub))
DFO_6_9<- DFO_6_9 %>%
  rename("Year"="subA",
         "Mean"="V2",
         "Lower"="V3",
         "Upper"="V4")
DFO_6_9$Type<-as.factor("DFO ages 6-9")

sub<-est_Sinclair_Z_NMFS_Spring_5_9$est.Sinclair.Z
subA<-est_Sinclair_Z_NMFS_Spring_5_9$plot.year
NMFS_Spring<-as.data.frame(cbind(subA,sub))
NMFS_Spring<- NMFS_Spring %>%
  rename("Year"="subA",
         "Mean"="V2",
         "Lower"="V3",
         "Upper"="V4")
NMFS_Spring$Type<-as.factor("NMFS Spring ages 5-9")

sub<-est_Sinclair_Z_NMFS_Fall_3_6$est.Sinclair.Z
subA<-est_Sinclair_Z_NMFS_Fall_3_6$plot.year
NMFS_Fall<-as.data.frame(cbind(subA,sub))
NMFS_Fall<- NMFS_Fall %>%
  rename("Year"="subA",
         "Mean"="V2",
         "Lower"="V3",
         "Upper"="V4")
NMFS_Fall$Type<-as.factor("NMFS Fall ages 3-6")


AllData<-rbind(DFO_6_9,NMFS_Spring,NMFS_Fall)

#Extracted years are in 0.5s. This just deletes the .5
AllData$Year<-AllData$Year-0.5

p<-ggplot(AllData,aes(x=Year,y=Mean,colour=Type))+
  geom_line()+
  geom_point()+
  geom_ribbon(aes(ymin=Lower,
                  ymax=Upper,
                  fill=Type),
                  alpha=0.5)+
  geom_hline(yintercept=0)+
  facet_wrap(~Type,nrow=3)+
  labs(y="Sinclair Z")+
  theme(legend.position="none")+
  theme_bw()
p

ggsave("DFO_NMFS_Spring_Fall_Sinclair_Z_Ribbon.png",path = "figures" ,plot=p)


